id: P007934
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W19224
  title: རྟེན་འབྲེལ་ཡིག་རྙིང་།
  author: ''
  volumes:
    cf8fb28939be40fba934f7d91efc9d7e:
      image_group_id: I1KG12582
      title: Volume 1 of rten 'brel yig rnying /
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
