id: P007934
initial_creation_type: ocr
source_metadata:
  id: bdr:W19224
  title: རྟེན་འབྲེལ་ཡིག་རྙིང་།
  author: ''
  volumes:
    55ac819190d84a5cba12de207d0e409b:
      image_group_id: I1KG12582
      title: ''
      volume_number: 1
      total_pages: 232
ebook_metadata:
  title: རྟེན་འབྲེལ་ཡིག་རྙིང་།
  author: ''
  sku: P007934
  cover: cover.jpg
  layers:
  - pagination
